namespace FYMKWebApplication5.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class C_Mentee : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.C_Mentee",
                c => new
                    {
                        id = c.Int(nullable: false, identity: true),
                        FirstName = c.String(),
                        LastName = c.String(),
                        Address1 = c.String(),
                        Address = c.String(),
                        City = c.String(),
                        State = c.String(),
                        PostalCode = c.String(),
                        Countries = c.String(),
                        Telephone = c.String(),
                        Email = c.String(),
                        Confirm = c.String(),
                        MyProperty = c.DateTime(nullable: false),
                        Gender = c.String(nullable: false),
                        EthicGroup = c.String(),
                        Prefenrene = c.String(),
                        YourLanguage = c.String(),
                        Role = c.Boolean(nullable: false),
                        PartT_Time = c.Boolean(nullable: false),
                        Graduated = c.Boolean(nullable: false),
                        Training = c.Boolean(nullable: false),
                        Working = c.Boolean(nullable: false),
                        Working_Part_Time = c.Boolean(nullable: false),
                        Unemployed = c.Boolean(nullable: false),
                        GSCE = c.Boolean(nullable: false),
                        A_Levels = c.Boolean(nullable: false),
                        Higher = c.Boolean(nullable: false),
                        NameAddress = c.String(),
                        NameAddres = c.String(),
                        NameAdre = c.String(),
                        Citt = c.String(),
                        Province = c.String(),
                        PostalCod = c.String(),
                        SelectedCountryIso32 = c.String(nullable: false),
                        MyPropert = c.DateTime(nullable: false),
                        MyProper = c.DateTime(nullable: false),
                        Comment = c.String(),
                        PleaseTellUs = c.String(),
                        Weekly = c.Boolean(nullable: false),
                        Fortnight = c.Boolean(nullable: false),
                        Monthly = c.Boolean(nullable: false),
                        ONE_HOUR = c.Boolean(nullable: false),
                        ONE_FIVE = c.Boolean(nullable: false),
                        TWO_HOUR = c.Boolean(nullable: false),
                        Skills = c.String(),
                        If_Yes = c.Boolean(nullable: false),
                        Education = c.Boolean(nullable: false),
                        Enterpreneurship = c.Boolean(nullable: false),
                        Employment = c.Boolean(nullable: false),
                        University = c.Boolean(nullable: false),
                        Building = c.Boolean(nullable: false),
                        Developing = c.Boolean(nullable: false),
                        Resilence = c.Boolean(nullable: false),
                        Volunteering = c.Boolean(nullable: false),
                        College = c.Boolean(nullable: false),
                        Career = c.Boolean(nullable: false),
                        CareerOptions = c.Boolean(nullable: false),
                        CV = c.Boolean(nullable: false),
                        Getting = c.Boolean(nullable: false),
                        Finding = c.Boolean(nullable: false),
                        ChangingCareer = c.Boolean(nullable: false),
                        Interview = c.Boolean(nullable: false),
                        Visual_Arts = c.Boolean(nullable: false),
                        Watching_Films = c.Boolean(nullable: false),
                        Creating_Videos = c.Boolean(nullable: false),
                        Reading_Fiction = c.Boolean(nullable: false),
                        Litary_Works = c.Boolean(nullable: false),
                        Sport = c.Boolean(nullable: false),
                        Electronic_Video_Game = c.Boolean(nullable: false),
                        Music = c.Boolean(nullable: false),
                        Baking = c.Boolean(nullable: false),
                        Cooking = c.Boolean(nullable: false),
                        Volunteeringg = c.Boolean(nullable: false),
                        ProfessionalInterest = c.String(),
                        Science = c.Boolean(nullable: false),
                        Information = c.Boolean(nullable: false),
                        FInancial = c.Boolean(nullable: false),
                        Educations = c.Boolean(nullable: false),
                        Business = c.Boolean(nullable: false),
                        Legal = c.Boolean(nullable: false),
                        HealthCare = c.Boolean(nullable: false),
                        Engineering = c.Boolean(nullable: false),
                        Non_Profit = c.Boolean(nullable: false),
                        Politics = c.Boolean(nullable: false),
                        Marketting = c.Boolean(nullable: false),
                        ProfessionalInterestt = c.Boolean(nullable: false),
                        Outgoing = c.Boolean(nullable: false),
                        Funny = c.Boolean(nullable: false),
                        Lively = c.Boolean(nullable: false),
                        Businesss = c.Boolean(nullable: false),
                        Construtive = c.Boolean(nullable: false),
                        Emphathetic = c.Boolean(nullable: false),
                        Intuitive = c.Boolean(nullable: false),
                        Passionate = c.Boolean(nullable: false),
                        Reserved = c.Boolean(nullable: false),
                        Reflective = c.Boolean(nullable: false),
                        Vibrant = c.Boolean(nullable: false),
                        Others = c.String(),
                        Criminal = c.String(),
                        References = c.String(),
                        Refenrece = c.String(),
                        Addres = c.String(),
                        Addre = c.String(),
                        Sity = c.String(),
                        Region = c.String(),
                        Postal = c.String(),
                        SelectedCountryIso3 = c.String(nullable: false),
                        Emai = c.String(),
                        Reference = c.String(),
                        Refenrec = c.String(),
                        Adde = c.String(),
                        Addr = c.String(),
                        zity = c.String(),
                        Regio = c.String(),
                        PostalCo = c.String(),
                        SelectedCountryIso33 = c.String(nullable: false),
                        Emaill = c.String(),
                        Telephonee = c.String(),
                        Note = c.String(),
                    })
                .PrimaryKey(t => t.id);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.C_Mentee");
        }
    }
}
