// <auto-generated />
namespace FYMKWebApplication4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewNewNewUp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewNewNewUp));
        
        string IMigrationMetadata.Id
        {
            get { return "202208012021554_NewNewNewUp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
