namespace FYMKWebApplication5.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Fymk : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Mentees",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        FirstName = c.String(),
                        LastName = c.String(),
                        Address1 = c.String(),
                        Address = c.String(),
                        City = c.String(),
                        State = c.String(),
                        PostalCode = c.Int(nullable: false),
                        Countries = c.String(),
                        Telephone = c.Int(nullable: false),
                        Email = c.String(),
                        Confirm = c.String(),
                        MyProperty = c.DateTime(nullable: false),
                        Gender = c.Boolean(nullable: false),
                        EthicGroup = c.String(),
                        Prefenrene = c.String(),
                        YourLanguage = c.String(),
                        Role = c.Boolean(nullable: false),
                        PartT_Time = c.Boolean(nullable: false),
                        Graduated = c.Boolean(nullable: false),
                        Training = c.Boolean(nullable: false),
                        Working = c.Boolean(nullable: false),
                        Working_Part_Time = c.Boolean(nullable: false),
                        Unemployed = c.Boolean(nullable: false),
                        GSCE = c.Boolean(nullable: false),
                        A_Levels = c.Boolean(nullable: false),
                        Higher = c.Boolean(nullable: false),
                        NameAddress = c.String(),
                        NameAddres = c.String(),
                        NameAdre = c.String(),
                        Citt = c.String(),
                        Province = c.String(),
                        PostalCod = c.Int(nullable: false),
                        SelectedCountryIso32 = c.String(nullable: false),
                        MyPropert = c.DateTime(nullable: false),
                        MyProper = c.DateTime(nullable: false),
                        Comment = c.String(),
                        PleaseTellUs = c.String(),
                        Weekly = c.Boolean(nullable: false),
                        Fortnight = c.Boolean(nullable: false),
                        Monthly = c.Boolean(nullable: false),
                        ONE_HOUR = c.Boolean(nullable: false),
                        ONE_FIVE = c.Boolean(nullable: false),
                        TWO_HOUR = c.Boolean(nullable: false),
                        Skills = c.String(),
                        If_Yes = c.Boolean(nullable: false),
                        Education = c.Boolean(nullable: false),
                        Enterpreneurship = c.Boolean(nullable: false),
                        Employment = c.Boolean(nullable: false),
                        University = c.Boolean(nullable: false),
                        Building = c.Boolean(nullable: false),
                        Developing = c.Boolean(nullable: false),
                        Resilence = c.Boolean(nullable: false),
                        Volunteering = c.Boolean(nullable: false),
                        College = c.Boolean(nullable: false),
                        Career = c.Boolean(nullable: false),
                        CareerOptions = c.Boolean(nullable: false),
                        CV = c.Boolean(nullable: false),
                        Getting = c.Boolean(nullable: false),
                        Finding = c.Boolean(nullable: false),
                        ChangingCareer = c.Boolean(nullable: false),
                        Interview = c.Boolean(nullable: false),
                        Visual_Arts = c.Boolean(nullable: false),
                        Watching_Films = c.Boolean(nullable: false),
                        Creating_Videos = c.Boolean(nullable: false),
                        Reading_Fiction = c.Boolean(nullable: false),
                        Litary_Works = c.Boolean(nullable: false),
                        Sport = c.Boolean(nullable: false),
                        Electronic_Video_Game = c.Boolean(nullable: false),
                        Music = c.Boolean(nullable: false),
                        Baking = c.Boolean(nullable: false),
                        Cooking = c.Boolean(nullable: false),
                        Volunteeringg = c.Boolean(nullable: false),
                        ProfessionalInterest = c.String(),
                        Science = c.Boolean(nullable: false),
                        Information = c.Boolean(nullable: false),
                        FInancial = c.Boolean(nullable: false),
                        Educations = c.Boolean(nullable: false),
                        Business = c.Boolean(nullable: false),
                        Legal = c.Boolean(nullable: false),
                        HealthCare = c.Boolean(nullable: false),
                        Engineering = c.Boolean(nullable: false),
                        Non_Profit = c.Boolean(nullable: false),
                        Politics = c.Boolean(nullable: false),
                        Marketting = c.Boolean(nullable: false),
                        ProfessionalInterestt = c.Boolean(nullable: false),
                        Outgoing = c.Boolean(nullable: false),
                        Funny = c.Boolean(nullable: false),
                        Lively = c.Boolean(nullable: false),
                        Businesss = c.Boolean(nullable: false),
                        Construtive = c.Boolean(nullable: false),
                        Emphathetic = c.Boolean(nullable: false),
                        Intuitive = c.Boolean(nullable: false),
                        Passionate = c.Boolean(nullable: false),
                        Reserved = c.Boolean(nullable: false),
                        Reflective = c.Boolean(nullable: false),
                        Vibrant = c.Boolean(nullable: false),
                        Others = c.String(),
                        Criminal = c.String(),
                        References = c.String(),
                        Refenrece = c.String(),
                        Addres = c.String(),
                        Addre = c.String(),
                        Sity = c.String(),
                        Region = c.String(),
                        Postal = c.Int(nullable: false),
                        SelectedCountryIso3 = c.String(nullable: false),
                        Emai = c.String(),
                        Reference = c.String(),
                        Refenrec = c.String(),
                        Adde = c.String(),
                        Addr = c.String(),
                        zity = c.String(),
                        Regio = c.String(),
                        PostalCo = c.Int(nullable: false),
                        SelectedCountryIso33 = c.String(nullable: false),
                        Emaill = c.String(),
                        Telephonee = c.Int(nullable: false),
                        Note = c.String(),
                        MentorId = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Mentors", t => t.MentorId, cascadeDelete: true)
                .Index(t => t.MentorId);
            
            CreateTable(
                "dbo.Mentors",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        FirstName = c.String(),
                        LastName = c.String(),
                        Address = c.String(),
                        Addresss = c.String(),
                        City = c.String(),
                        State = c.String(),
                        PostalCode = c.String(),
                        Country = c.String(),
                        Telephone = c.Int(nullable: false),
                        Email = c.String(),
                        ConrirmEmail = c.String(),
                        Date = c.DateTime(nullable: false),
                        Gender = c.String(nullable: false),
                        PrefrenceOnGender = c.String(),
                        FirstLanguage = c.String(),
                        CriminalConvivtion = c.String(),
                        DBSCertificate = c.String(),
                        UpdatedDBS = c.String(),
                        GCSE = c.Boolean(nullable: false),
                        ALevel = c.Boolean(nullable: false),
                        Higher = c.Boolean(nullable: false),
                        StudyingOrWorking = c.String(),
                        InstituteOrUniversity = c.String(),
                        CourseStudying = c.String(),
                        StartDate = c.DateTime(nullable: false),
                        EndDate = c.DateTime(nullable: false),
                        Volunteer = c.String(),
                        WhyYouWantToMentor = c.String(),
                        YourExperience = c.String(),
                        WhenAreYouAvailable = c.String(),
                        SkillHobbies = c.String(),
                        SpecialNeed = c.String(),
                        Comment = c.String(),
                        Education = c.Boolean(nullable: false),
                        Enterpreneurship = c.Boolean(nullable: false),
                        Employement = c.Boolean(nullable: false),
                        Developing_Resilence = c.Boolean(nullable: false),
                        Volunteering = c.Boolean(nullable: false),
                        Changing_Career = c.Boolean(nullable: false),
                        Building_Confidence = c.Boolean(nullable: false),
                        Getting_Involved_In_Community_Work = c.Boolean(nullable: false),
                        Career_Without_University = c.Boolean(nullable: false),
                        Finding_Jobs_Locally = c.Boolean(nullable: false),
                        Developing_A_Professional_Network = c.Boolean(nullable: false),
                        CV_Writting = c.Boolean(nullable: false),
                        University_Applications = c.Boolean(nullable: false),
                        Interview_Skills = c.Boolean(nullable: false),
                        MyProperty = c.Boolean(nullable: false),
                        Visual_Arts = c.Boolean(nullable: false),
                        Watching_Films = c.Boolean(nullable: false),
                        Creating_Videos = c.Boolean(nullable: false),
                        Reading_Fiction = c.Boolean(nullable: false),
                        Litary_Works = c.Boolean(nullable: false),
                        Sport = c.Boolean(nullable: false),
                        Electronic_Video_Game = c.Boolean(nullable: false),
                        Music = c.Boolean(nullable: false),
                        Baking = c.Boolean(nullable: false),
                        Cooking = c.Boolean(nullable: false),
                        Volunteeringg = c.Boolean(nullable: false),
                        ProfessionalInterest = c.String(),
                        Science = c.Boolean(nullable: false),
                        Information = c.Boolean(nullable: false),
                        FInancial = c.Boolean(nullable: false),
                        Educations = c.Boolean(nullable: false),
                        Business = c.Boolean(nullable: false),
                        Legal = c.Boolean(nullable: false),
                        HealthCare = c.Boolean(nullable: false),
                        Engineering = c.Boolean(nullable: false),
                        Non_Profit = c.Boolean(nullable: false),
                        Politics = c.Boolean(nullable: false),
                        Marketting = c.Boolean(nullable: false),
                        Other = c.String(),
                        Outgoing = c.Boolean(nullable: false),
                        Funny = c.Boolean(nullable: false),
                        Lively = c.Boolean(nullable: false),
                        Businesss = c.Boolean(nullable: false),
                        Construtive = c.Boolean(nullable: false),
                        Emphathetic = c.Boolean(nullable: false),
                        Intuitive = c.Boolean(nullable: false),
                        Passionate = c.Boolean(nullable: false),
                        Reserved = c.Boolean(nullable: false),
                        Reflective = c.Boolean(nullable: false),
                        Vibrant = c.Boolean(nullable: false),
                        Others = c.String(),
                        Refenrence = c.String(),
                        Addressss = c.String(),
                        Address2 = c.String(),
                        Cityy = c.String(),
                        Region = c.String(),
                        Code = c.String(),
                        Countryy = c.String(),
                        Telephonee = c.Int(nullable: false),
                        Refenrence2 = c.String(),
                        Addresssss = c.String(),
                        AddressTwo = c.String(),
                        Cityyy = c.String(),
                        Regionn = c.String(),
                        Codee = c.String(),
                        Countryyy = c.String(),
                        Telephoneee = c.Int(nullable: false),
                        FinalNote = c.String(),
                        GDPR = c.Boolean(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Mentees", "MentorId", "dbo.Mentors");
            DropIndex("dbo.Mentees", new[] { "MentorId" });
            DropTable("dbo.Mentors");
            DropTable("dbo.Mentees");
        }
    }
}
